name: conda_build_and_upload
on:
  push:
    branches:
      - master
jobs:
  conda_build_and_upload:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
      - name: prepare build environment
        run: |
          $CONDA/bin/conda create -n conda_build conda-build conda-verify anaconda-client
      - name: build package
        run: |
          $CONDA/bin/conda init bash
          $CONDA/bin/conda activate conda_build
          $CONDA/bin/conda build -c lcls-ii -c conda-forge recipe
